###
GET http://localhost:3000/seats
###
POST http://localhost:3000/purchase
Content-Type: application/json

{
  "row": 8,
  "column": 2
}
###
POST http://localhost:3000/return
Content-Type: application/json

{
    "token": "ccf8a51b-9b54-48b2-8cf4-28743e7a650d"
}
###
GET http://localhost:3000/stats?password=super_secret